import {
  PROCORE_CLIENT_ID,
  PROCORE_CLIENT_SECRET,
  PROCORE_COMPANY_ID,
  OPENAI_API_KEY,
  PROCORE_REDIRECT_URI,
} from "./config";

console.log("PROCORE_CLIENT_ID:", PROCORE_CLIENT_ID);
console.log("PROCORE_COMPANY_ID:", PROCORE_COMPANY_ID);
console.log("PROCORE_REDIRECT_URI:", PROCORE_REDIRECT_URI);
console.log("Has OPENAI_API_KEY set?", OPENAI_API_KEY ? "yes" : "no");
